/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoyageRouteImport } from './routes/voyage'
import { Route as VieAdminRouteImport } from './routes/vie-admin'
import { Route as SsoRouteImport } from './routes/sso'
import { Route as ProductiviteRouteImport } from './routes/productivite'
import { Route as ParrainageRouteImport } from './routes/parrainage'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PaperasseRouteImport } from './routes/paperasse'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MesOutilsRouteImport } from './routes/mes-outils'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContenuRouteImport } from './routes/contenu'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as OutilsFinzyRouteImport } from './routes/outils.finzy'
import { Route as FinanceBudgetPrevisionnelRouteImport } from './routes/finance.budget-previsionnel'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiSsoRouteImport } from './routes/api.sso'
import { Route as ApiSkillRouteImport } from './routes/api.skill'
import { Route as ApiEntitlementsRouteImport } from './routes/api.entitlements'
import { Route as ApiAgentRouteImport } from './routes/api.agent'
import { Route as ApiAccountRouteImport } from './routes/api.account'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const VoyageRoute = VoyageRouteImport.update({
  id: '/voyage',
  path: '/voyage',
  getParentRoute: () => rootRouteImport,
} as any)
const VieAdminRoute = VieAdminRouteImport.update({
  id: '/vie-admin',
  path: '/vie-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoRoute = SsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductiviteRoute = ProductiviteRouteImport.update({
  id: '/productivite',
  path: '/productivite',
  getParentRoute: () => rootRouteImport,
} as any)
const ParrainageRoute = ParrainageRouteImport.update({
  id: '/parrainage',
  path: '/parrainage',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperasseRoute = PaperasseRouteImport.update({
  id: '/paperasse',
  path: '/paperasse',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MesOutilsRoute = MesOutilsRouteImport.update({
  id: '/mes-outils',
  path: '/mes-outils',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContenuRoute = ContenuRouteImport.update({
  id: '/contenu',
  path: '/contenu',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsFinzyRoute = OutilsFinzyRouteImport.update({
  id: '/outils/finzy',
  path: '/outils/finzy',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBudgetPrevisionnelRoute =
  FinanceBudgetPrevisionnelRouteImport.update({
    id: '/finance/budget-previsionnel',
    path: '/finance/budget-previsionnel',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const ApiSsoRoute = ApiSsoRouteImport.update({
  id: '/api/sso',
  path: '/api/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillRoute = ApiSkillRouteImport.update({
  id: '/api/skill',
  path: '/api/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEntitlementsRoute = ApiEntitlementsRouteImport.update({
  id: '/api/entitlements',
  path: '/api/entitlements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountRoute = ApiAccountRouteImport.update({
  id: '/api/account',
  path: '/api/account',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/business': typeof BusinessRoute
  '/cgu': typeof CguRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/contenu': typeof ContenuRoute
  '/cookies': typeof CookiesRoute
  '/evenements': typeof EvenementsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-outils': typeof MesOutilsRoute
  '/onboarding': typeof OnboardingRoute
  '/paperasse': typeof PaperasseRoute
  '/parametres': typeof ParametresRoute
  '/parrainage': typeof ParrainageRoute
  '/productivite': typeof ProductiviteRoute
  '/sso': typeof SsoRoute
  '/vie-admin': typeof VieAdminRoute
  '/voyage': typeof VoyageRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/account': typeof ApiAccountRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/entitlements': typeof ApiEntitlementsRoute
  '/api/skill': typeof ApiSkillRoute
  '/api/sso': typeof ApiSsoRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/finance/budget-previsionnel': typeof FinanceBudgetPrevisionnelRoute
  '/outils/finzy': typeof OutilsFinzyRoute
  '/finance/': typeof FinanceIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/business': typeof BusinessRoute
  '/cgu': typeof CguRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/contenu': typeof ContenuRoute
  '/cookies': typeof CookiesRoute
  '/evenements': typeof EvenementsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-outils': typeof MesOutilsRoute
  '/onboarding': typeof OnboardingRoute
  '/paperasse': typeof PaperasseRoute
  '/parametres': typeof ParametresRoute
  '/parrainage': typeof ParrainageRoute
  '/productivite': typeof ProductiviteRoute
  '/sso': typeof SsoRoute
  '/vie-admin': typeof VieAdminRoute
  '/voyage': typeof VoyageRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/account': typeof ApiAccountRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/entitlements': typeof ApiEntitlementsRoute
  '/api/skill': typeof ApiSkillRoute
  '/api/sso': typeof ApiSsoRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/finance/budget-previsionnel': typeof FinanceBudgetPrevisionnelRoute
  '/outils/finzy': typeof OutilsFinzyRoute
  '/finance': typeof FinanceIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/business': typeof BusinessRoute
  '/cgu': typeof CguRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/contenu': typeof ContenuRoute
  '/cookies': typeof CookiesRoute
  '/evenements': typeof EvenementsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-outils': typeof MesOutilsRoute
  '/onboarding': typeof OnboardingRoute
  '/paperasse': typeof PaperasseRoute
  '/parametres': typeof ParametresRoute
  '/parrainage': typeof ParrainageRoute
  '/productivite': typeof ProductiviteRoute
  '/sso': typeof SsoRoute
  '/vie-admin': typeof VieAdminRoute
  '/voyage': typeof VoyageRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/account': typeof ApiAccountRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/entitlements': typeof ApiEntitlementsRoute
  '/api/skill': typeof ApiSkillRoute
  '/api/sso': typeof ApiSsoRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/finance/budget-previsionnel': typeof FinanceBudgetPrevisionnelRoute
  '/outils/finzy': typeof OutilsFinzyRoute
  '/finance/': typeof FinanceIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/business'
    | '/cgu'
    | '/checkout'
    | '/confidentialite'
    | '/contenu'
    | '/cookies'
    | '/evenements'
    | '/login'
    | '/mcp'
    | '/mentions-legales'
    | '/mes-outils'
    | '/onboarding'
    | '/paperasse'
    | '/parametres'
    | '/parrainage'
    | '/productivite'
    | '/sso'
    | '/vie-admin'
    | '/voyage'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/account'
    | '/api/agent'
    | '/api/entitlements'
    | '/api/skill'
    | '/api/sso'
    | '/checkout/return'
    | '/finance/budget-previsionnel'
    | '/outils/finzy'
    | '/finance/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/business'
    | '/cgu'
    | '/checkout'
    | '/confidentialite'
    | '/contenu'
    | '/cookies'
    | '/evenements'
    | '/login'
    | '/mcp'
    | '/mentions-legales'
    | '/mes-outils'
    | '/onboarding'
    | '/paperasse'
    | '/parametres'
    | '/parrainage'
    | '/productivite'
    | '/sso'
    | '/vie-admin'
    | '/voyage'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/account'
    | '/api/agent'
    | '/api/entitlements'
    | '/api/skill'
    | '/api/sso'
    | '/checkout/return'
    | '/finance/budget-previsionnel'
    | '/outils/finzy'
    | '/finance'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/business'
    | '/cgu'
    | '/checkout'
    | '/confidentialite'
    | '/contenu'
    | '/cookies'
    | '/evenements'
    | '/login'
    | '/mcp'
    | '/mentions-legales'
    | '/mes-outils'
    | '/onboarding'
    | '/paperasse'
    | '/parametres'
    | '/parrainage'
    | '/productivite'
    | '/sso'
    | '/vie-admin'
    | '/voyage'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/account'
    | '/api/agent'
    | '/api/entitlements'
    | '/api/skill'
    | '/api/sso'
    | '/checkout/return'
    | '/finance/budget-previsionnel'
    | '/outils/finzy'
    | '/finance/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BusinessRoute: typeof BusinessRoute
  CguRoute: typeof CguRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContenuRoute: typeof ContenuRoute
  CookiesRoute: typeof CookiesRoute
  EvenementsRoute: typeof EvenementsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MesOutilsRoute: typeof MesOutilsRoute
  OnboardingRoute: typeof OnboardingRoute
  PaperasseRoute: typeof PaperasseRoute
  ParametresRoute: typeof ParametresRoute
  ParrainageRoute: typeof ParrainageRoute
  ProductiviteRoute: typeof ProductiviteRoute
  SsoRoute: typeof SsoRoute
  VieAdminRoute: typeof VieAdminRoute
  VoyageRoute: typeof VoyageRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAccountRoute: typeof ApiAccountRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiEntitlementsRoute: typeof ApiEntitlementsRoute
  ApiSkillRoute: typeof ApiSkillRoute
  ApiSsoRoute: typeof ApiSsoRoute
  FinanceBudgetPrevisionnelRoute: typeof FinanceBudgetPrevisionnelRoute
  OutilsFinzyRoute: typeof OutilsFinzyRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voyage': {
      id: '/voyage'
      path: '/voyage'
      fullPath: '/voyage'
      preLoaderRoute: typeof VoyageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vie-admin': {
      id: '/vie-admin'
      path: '/vie-admin'
      fullPath: '/vie-admin'
      preLoaderRoute: typeof VieAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso': {
      id: '/sso'
      path: '/sso'
      fullPath: '/sso'
      preLoaderRoute: typeof SsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productivite': {
      id: '/productivite'
      path: '/productivite'
      fullPath: '/productivite'
      preLoaderRoute: typeof ProductiviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parrainage': {
      id: '/parrainage'
      path: '/parrainage'
      fullPath: '/parrainage'
      preLoaderRoute: typeof ParrainageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paperasse': {
      id: '/paperasse'
      path: '/paperasse'
      fullPath: '/paperasse'
      preLoaderRoute: typeof PaperasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-outils': {
      id: '/mes-outils'
      path: '/mes-outils'
      fullPath: '/mes-outils'
      preLoaderRoute: typeof MesOutilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contenu': {
      id: '/contenu'
      path: '/contenu'
      fullPath: '/contenu'
      preLoaderRoute: typeof ContenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils/finzy': {
      id: '/outils/finzy'
      path: '/outils/finzy'
      fullPath: '/outils/finzy'
      preLoaderRoute: typeof OutilsFinzyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/budget-previsionnel': {
      id: '/finance/budget-previsionnel'
      path: '/finance/budget-previsionnel'
      fullPath: '/finance/budget-previsionnel'
      preLoaderRoute: typeof FinanceBudgetPrevisionnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/api/sso': {
      id: '/api/sso'
      path: '/api/sso'
      fullPath: '/api/sso'
      preLoaderRoute: typeof ApiSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skill': {
      id: '/api/skill'
      path: '/api/skill'
      fullPath: '/api/skill'
      preLoaderRoute: typeof ApiSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/entitlements': {
      id: '/api/entitlements'
      path: '/api/entitlements'
      fullPath: '/api/entitlements'
      preLoaderRoute: typeof ApiEntitlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account': {
      id: '/api/account'
      path: '/api/account'
      fullPath: '/api/account'
      preLoaderRoute: typeof ApiAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BusinessRoute: BusinessRoute,
  CguRoute: CguRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContenuRoute: ContenuRoute,
  CookiesRoute: CookiesRoute,
  EvenementsRoute: EvenementsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MesOutilsRoute: MesOutilsRoute,
  OnboardingRoute: OnboardingRoute,
  PaperasseRoute: PaperasseRoute,
  ParametresRoute: ParametresRoute,
  ParrainageRoute: ParrainageRoute,
  ProductiviteRoute: ProductiviteRoute,
  SsoRoute: SsoRoute,
  VieAdminRoute: VieAdminRoute,
  VoyageRoute: VoyageRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAccountRoute: ApiAccountRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiEntitlementsRoute: ApiEntitlementsRoute,
  ApiSkillRoute: ApiSkillRoute,
  ApiSsoRoute: ApiSsoRoute,
  FinanceBudgetPrevisionnelRoute: FinanceBudgetPrevisionnelRoute,
  OutilsFinzyRoute: OutilsFinzyRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
