/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentionsRouteImport } from './routes/mentions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppParametresRouteImport } from './routes/app.parametres'
import { Route as AppHistoriqueRouteImport } from './routes/app.historique'
import { Route as AppEquipeRouteImport } from './routes/app.equipe'

const MentionsRoute = MentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/app/parametres',
  path: '/app/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoriqueRoute = AppHistoriqueRouteImport.update({
  id: '/app/historique',
  path: '/app/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/app/equipe',
  path: '/app/equipe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mentions': typeof MentionsRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/historique': typeof AppHistoriqueRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mentions': typeof MentionsRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/historique': typeof AppHistoriqueRoute
  '/app/parametres': typeof AppParametresRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mentions': typeof MentionsRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/historique': typeof AppHistoriqueRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mentions'
    | '/app/equipe'
    | '/app/historique'
    | '/app/parametres'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mentions'
    | '/app/equipe'
    | '/app/historique'
    | '/app/parametres'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/mentions'
    | '/app/equipe'
    | '/app/historique'
    | '/app/parametres'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MentionsRoute: typeof MentionsRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppHistoriqueRoute: typeof AppHistoriqueRoute
  AppParametresRoute: typeof AppParametresRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentions': {
      id: '/mentions'
      path: '/mentions'
      fullPath: '/mentions'
      preLoaderRoute: typeof MentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/parametres': {
      id: '/app/parametres'
      path: '/app/parametres'
      fullPath: '/app/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/historique': {
      id: '/app/historique'
      path: '/app/historique'
      fullPath: '/app/historique'
      preLoaderRoute: typeof AppHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/app/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MentionsRoute: MentionsRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppHistoriqueRoute: AppHistoriqueRoute,
  AppParametresRoute: AppParametresRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
