/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentionsRouteImport } from './routes/mentions'
import { Route as AgRouteImport } from './routes/ag'
import { Route as IndexRouteImport } from './routes/index'

const MentionsRoute = MentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const AgRoute = AgRouteImport.update({
  id: '/ag',
  path: '/ag',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ag': typeof AgRoute
  '/mentions': typeof MentionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ag': typeof AgRoute
  '/mentions': typeof MentionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ag': typeof AgRoute
  '/mentions': typeof MentionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ag' | '/mentions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ag' | '/mentions'
  id: '__root__' | '/' | '/ag' | '/mentions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgRoute: typeof AgRoute
  MentionsRoute: typeof MentionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentions': {
      id: '/mentions'
      path: '/mentions'
      fullPath: '/mentions'
      preLoaderRoute: typeof MentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ag': {
      id: '/ag'
      path: '/ag'
      fullPath: '/ag'
      preLoaderRoute: typeof AgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgRoute: AgRoute,
  MentionsRoute: MentionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
