/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as PourFiduciairesRouteImport } from './routes/pour-fiduciaires'
import { Route as MentionsRouteImport } from './routes/mentions'
import { Route as ComparerRouteImport } from './routes/comparer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FIdRouteImport } from './routes/f.$id'

const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const PourFiduciairesRoute = PourFiduciairesRouteImport.update({
  id: '/pour-fiduciaires',
  path: '/pour-fiduciaires',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsRoute = MentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparerRoute = ComparerRouteImport.update({
  id: '/comparer',
  path: '/comparer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FIdRoute = FIdRouteImport.update({
  id: '/f/$id',
  path: '/f/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparer': typeof ComparerRoute
  '/mentions': typeof MentionsRoute
  '/pour-fiduciaires': typeof PourFiduciairesRoute
  '/recherche': typeof RechercheRoute
  '/f/$id': typeof FIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparer': typeof ComparerRoute
  '/mentions': typeof MentionsRoute
  '/pour-fiduciaires': typeof PourFiduciairesRoute
  '/recherche': typeof RechercheRoute
  '/f/$id': typeof FIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparer': typeof ComparerRoute
  '/mentions': typeof MentionsRoute
  '/pour-fiduciaires': typeof PourFiduciairesRoute
  '/recherche': typeof RechercheRoute
  '/f/$id': typeof FIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comparer'
    | '/mentions'
    | '/pour-fiduciaires'
    | '/recherche'
    | '/f/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comparer'
    | '/mentions'
    | '/pour-fiduciaires'
    | '/recherche'
    | '/f/$id'
  id:
    | '__root__'
    | '/'
    | '/comparer'
    | '/mentions'
    | '/pour-fiduciaires'
    | '/recherche'
    | '/f/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparerRoute: typeof ComparerRoute
  MentionsRoute: typeof MentionsRoute
  PourFiduciairesRoute: typeof PourFiduciairesRoute
  RechercheRoute: typeof RechercheRoute
  FIdRoute: typeof FIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pour-fiduciaires': {
      id: '/pour-fiduciaires'
      path: '/pour-fiduciaires'
      fullPath: '/pour-fiduciaires'
      preLoaderRoute: typeof PourFiduciairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions': {
      id: '/mentions'
      path: '/mentions'
      fullPath: '/mentions'
      preLoaderRoute: typeof MentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparer': {
      id: '/comparer'
      path: '/comparer'
      fullPath: '/comparer'
      preLoaderRoute: typeof ComparerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$id': {
      id: '/f/$id'
      path: '/f/$id'
      fullPath: '/f/$id'
      preLoaderRoute: typeof FIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparerRoute: ComparerRoute,
  MentionsRoute: MentionsRoute,
  PourFiduciairesRoute: PourFiduciairesRoute,
  RechercheRoute: RechercheRoute,
  FIdRoute: FIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
