// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

function readEnv() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || (typeof process !== 'undefined' ? process.env.SUPABASE_URL : undefined);
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || (typeof process !== 'undefined' ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined);
  return { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY };
}

export function isSupabaseConfigured(): boolean {
  const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = readEnv();
  return Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
}

function createSupabaseClient(): SupabaseClient<Database> {
  const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = readEnv();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    console.warn(`[Supabase] Missing env: ${missing.join(', ')}. Auth cloud disabled.`);
    // Placeholder URL so createClient doesn't throw; calls will fail softly.
    return createClient<Database>('https://placeholder.supabase.co', 'public-anon-key', {
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: SupabaseClient<Database> | undefined;

export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop) {
    if (!_supabase) _supabase = createSupabaseClient();
    const val = Reflect.get(_supabase, prop, _supabase);
    return typeof val === "function" ? val.bind(_supabase) : val;
  },
});
