/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentionsRouteImport } from './routes/mentions'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppParametresRouteImport } from './routes/app.parametres'
import { Route as AppMembresRouteImport } from './routes/app.membres'
import { Route as AppCotisationsRouteImport } from './routes/app.cotisations'
import { Route as AppCheckinRouteImport } from './routes/app.checkin'

const MentionsRoute = MentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppMembresRoute = AppMembresRouteImport.update({
  id: '/membres',
  path: '/membres',
  getParentRoute: () => AppRoute,
} as any)
const AppCotisationsRoute = AppCotisationsRouteImport.update({
  id: '/cotisations',
  path: '/cotisations',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/mentions': typeof MentionsRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/cotisations': typeof AppCotisationsRoute
  '/app/membres': typeof AppMembresRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mentions': typeof MentionsRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/cotisations': typeof AppCotisationsRoute
  '/app/membres': typeof AppMembresRoute
  '/app/parametres': typeof AppParametresRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/mentions': typeof MentionsRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/cotisations': typeof AppCotisationsRoute
  '/app/membres': typeof AppMembresRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/mentions'
    | '/app/checkin'
    | '/app/cotisations'
    | '/app/membres'
    | '/app/parametres'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mentions'
    | '/app/checkin'
    | '/app/cotisations'
    | '/app/membres'
    | '/app/parametres'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/mentions'
    | '/app/checkin'
    | '/app/cotisations'
    | '/app/membres'
    | '/app/parametres'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  MentionsRoute: typeof MentionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentions': {
      id: '/mentions'
      path: '/mentions'
      fullPath: '/mentions'
      preLoaderRoute: typeof MentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parametres': {
      id: '/app/parametres'
      path: '/parametres'
      fullPath: '/app/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/membres': {
      id: '/app/membres'
      path: '/membres'
      fullPath: '/app/membres'
      preLoaderRoute: typeof AppMembresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cotisations': {
      id: '/app/cotisations'
      path: '/cotisations'
      fullPath: '/app/cotisations'
      preLoaderRoute: typeof AppCotisationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkin': {
      id: '/app/checkin'
      path: '/checkin'
      fullPath: '/app/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCheckinRoute: typeof AppCheckinRoute
  AppCotisationsRoute: typeof AppCotisationsRoute
  AppMembresRoute: typeof AppMembresRoute
  AppParametresRoute: typeof AppParametresRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckinRoute: AppCheckinRoute,
  AppCotisationsRoute: AppCotisationsRoute,
  AppMembresRoute: AppMembresRoute,
  AppParametresRoute: AppParametresRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  MentionsRoute: MentionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
