/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedFusionfitRouteImport } from './routes/_authenticated.fusionfit'
import { Route as AuthenticatedFusionfitIndexRouteImport } from './routes/_authenticated.fusionfit.index'
import { Route as AuthenticatedFusionfitAbonnementRouteImport } from './routes/_authenticated.fusionfit.abonnement'
import { Route as AuthenticatedFusionfitBibliothequeRouteImport } from './routes/_authenticated.fusionfit.bibliotheque'
import { Route as AuthenticatedFusionfitCoachRouteImport } from './routes/_authenticated.fusionfit.coach'
import { Route as AuthenticatedFusionfitCreneauxRouteImport } from './routes/_authenticated.fusionfit.creneaux'
import { Route as AuthenticatedFusionfitEscouadeRouteImport } from './routes/_authenticated.fusionfit.escouade'
import { Route as AuthenticatedFusionfitMessagerieRouteImport } from './routes/_authenticated.fusionfit.messagerie'
import { Route as AuthenticatedFusionfitOnboardingRouteImport } from './routes/_authenticated.fusionfit.onboarding'
import { Route as AuthenticatedFusionfitProfilRouteImport } from './routes/_authenticated.fusionfit.profil'
import { Route as AuthenticatedFusionfitRoutineRouteImport } from './routes/_authenticated.fusionfit.routine'
import { Route as AuthenticatedFusionfitStatsRouteImport } from './routes/_authenticated.fusionfit.stats'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api.webhooks.stripe'
import { Route as AuthenticatedFusionfitEscouadeAbonneIdRouteImport } from './routes/_authenticated.fusionfit.escouade.$abonneId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFusionfitRoute = AuthenticatedFusionfitRouteImport.update({
  id: '/fusionfit',
  path: '/fusionfit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFusionfitIndexRoute =
  AuthenticatedFusionfitIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFusionfitRoute,
  } as any)
const AuthenticatedFusionfitAbonnementRoute =
  AuthenticatedFusionfitAbonnementRouteImport.update({
    id: '/abonnement',
    path: '/abonnement',
    getParentRoute: () => AuthenticatedFusionfitRoute,
  } as any)
const AuthenticatedFusionfitBibliothequeRoute =
  AuthenticatedFusionfitBibliothequeRouteImport.update({
    id: '/bibliotheque',
    path: '/bibliotheque',
    getParentRoute: () => AuthenticatedFusionfitRoute,
  } as any)
const AuthenticatedFusionfitCoachRoute =
  AuthenticatedFusionfitCoachRouteImport.update({
    id: '/coach',
    path: '/coach',
    getParentRoute: () => AuthenticatedFusionfitRoute,
  } as any)
const AuthenticatedFusionfitCreneauxRoute =
  AuthenticatedFusionfitCreneauxRouteImport.update({
    id: '/creneaux',
    path: '/creneaux',
    getParentRoute: () => AuthenticatedFusionfitRoute,
  } as any)
const AuthenticatedFusionfitEscouadeRoute =
  AuthenticatedFusionfitEscouadeRouteImport.update({
    id: '/escouade',
    path: '/escouade',
    getParentRoute: () => AuthenticatedFusionfitRoute,
  } as any)
const AuthenticatedFusionfitMessagerieRoute =
  AuthenticatedFusionfitMessagerieRouteImport.update({
    id: '/messagerie',
    path: '/messagerie',
    getParentRoute: () => AuthenticatedFusionfitRoute,
  } as any)
const AuthenticatedFusionfitOnboardingRoute =
  AuthenticatedFusionfitOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedFusionfitRoute,
  } as any)
const AuthenticatedFusionfitProfilRoute =
  AuthenticatedFusionfitProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedFusionfitRoute,
  } as any)
const AuthenticatedFusionfitRoutineRoute =
  AuthenticatedFusionfitRoutineRouteImport.update({
    id: '/routine',
    path: '/routine',
    getParentRoute: () => AuthenticatedFusionfitRoute,
  } as any)
const AuthenticatedFusionfitStatsRoute =
  AuthenticatedFusionfitStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedFusionfitRoute,
  } as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFusionfitEscouadeAbonneIdRoute =
  AuthenticatedFusionfitEscouadeAbonneIdRouteImport.update({
    id: '/$abonneId',
    path: '/$abonneId',
    getParentRoute: () => AuthenticatedFusionfitEscouadeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/fusionfit': typeof AuthenticatedFusionfitRouteWithChildren
  '/fusionfit/abonnement': typeof AuthenticatedFusionfitAbonnementRoute
  '/fusionfit/bibliotheque': typeof AuthenticatedFusionfitBibliothequeRoute
  '/fusionfit/coach': typeof AuthenticatedFusionfitCoachRoute
  '/fusionfit/creneaux': typeof AuthenticatedFusionfitCreneauxRoute
  '/fusionfit/escouade': typeof AuthenticatedFusionfitEscouadeRouteWithChildren
  '/fusionfit/messagerie': typeof AuthenticatedFusionfitMessagerieRoute
  '/fusionfit/onboarding': typeof AuthenticatedFusionfitOnboardingRoute
  '/fusionfit/profil': typeof AuthenticatedFusionfitProfilRoute
  '/fusionfit/routine': typeof AuthenticatedFusionfitRoutineRoute
  '/fusionfit/stats': typeof AuthenticatedFusionfitStatsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/fusionfit/': typeof AuthenticatedFusionfitIndexRoute
  '/fusionfit/escouade/$abonneId': typeof AuthenticatedFusionfitEscouadeAbonneIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/fusionfit/abonnement': typeof AuthenticatedFusionfitAbonnementRoute
  '/fusionfit/bibliotheque': typeof AuthenticatedFusionfitBibliothequeRoute
  '/fusionfit/coach': typeof AuthenticatedFusionfitCoachRoute
  '/fusionfit/creneaux': typeof AuthenticatedFusionfitCreneauxRoute
  '/fusionfit/escouade': typeof AuthenticatedFusionfitEscouadeRouteWithChildren
  '/fusionfit/messagerie': typeof AuthenticatedFusionfitMessagerieRoute
  '/fusionfit/onboarding': typeof AuthenticatedFusionfitOnboardingRoute
  '/fusionfit/profil': typeof AuthenticatedFusionfitProfilRoute
  '/fusionfit/routine': typeof AuthenticatedFusionfitRoutineRoute
  '/fusionfit/stats': typeof AuthenticatedFusionfitStatsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/fusionfit': typeof AuthenticatedFusionfitIndexRoute
  '/fusionfit/escouade/$abonneId': typeof AuthenticatedFusionfitEscouadeAbonneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/fusionfit': typeof AuthenticatedFusionfitRouteWithChildren
  '/_authenticated/fusionfit/abonnement': typeof AuthenticatedFusionfitAbonnementRoute
  '/_authenticated/fusionfit/bibliotheque': typeof AuthenticatedFusionfitBibliothequeRoute
  '/_authenticated/fusionfit/coach': typeof AuthenticatedFusionfitCoachRoute
  '/_authenticated/fusionfit/creneaux': typeof AuthenticatedFusionfitCreneauxRoute
  '/_authenticated/fusionfit/escouade': typeof AuthenticatedFusionfitEscouadeRouteWithChildren
  '/_authenticated/fusionfit/messagerie': typeof AuthenticatedFusionfitMessagerieRoute
  '/_authenticated/fusionfit/onboarding': typeof AuthenticatedFusionfitOnboardingRoute
  '/_authenticated/fusionfit/profil': typeof AuthenticatedFusionfitProfilRoute
  '/_authenticated/fusionfit/routine': typeof AuthenticatedFusionfitRoutineRoute
  '/_authenticated/fusionfit/stats': typeof AuthenticatedFusionfitStatsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/_authenticated/fusionfit/': typeof AuthenticatedFusionfitIndexRoute
  '/_authenticated/fusionfit/escouade/$abonneId': typeof AuthenticatedFusionfitEscouadeAbonneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/fusionfit'
    | '/fusionfit/abonnement'
    | '/fusionfit/bibliotheque'
    | '/fusionfit/coach'
    | '/fusionfit/creneaux'
    | '/fusionfit/escouade'
    | '/fusionfit/messagerie'
    | '/fusionfit/onboarding'
    | '/fusionfit/profil'
    | '/fusionfit/routine'
    | '/fusionfit/stats'
    | '/api/webhooks/stripe'
    | '/fusionfit/'
    | '/fusionfit/escouade/$abonneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/fusionfit/abonnement'
    | '/fusionfit/bibliotheque'
    | '/fusionfit/coach'
    | '/fusionfit/creneaux'
    | '/fusionfit/escouade'
    | '/fusionfit/messagerie'
    | '/fusionfit/onboarding'
    | '/fusionfit/profil'
    | '/fusionfit/routine'
    | '/fusionfit/stats'
    | '/api/webhooks/stripe'
    | '/fusionfit'
    | '/fusionfit/escouade/$abonneId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/fusionfit'
    | '/_authenticated/fusionfit/abonnement'
    | '/_authenticated/fusionfit/bibliotheque'
    | '/_authenticated/fusionfit/coach'
    | '/_authenticated/fusionfit/creneaux'
    | '/_authenticated/fusionfit/escouade'
    | '/_authenticated/fusionfit/messagerie'
    | '/_authenticated/fusionfit/onboarding'
    | '/_authenticated/fusionfit/profil'
    | '/_authenticated/fusionfit/routine'
    | '/_authenticated/fusionfit/stats'
    | '/api/webhooks/stripe'
    | '/_authenticated/fusionfit/'
    | '/_authenticated/fusionfit/escouade/$abonneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fusionfit': {
      id: '/_authenticated/fusionfit'
      path: '/fusionfit'
      fullPath: '/fusionfit'
      preLoaderRoute: typeof AuthenticatedFusionfitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fusionfit/': {
      id: '/_authenticated/fusionfit/'
      path: '/'
      fullPath: '/fusionfit/'
      preLoaderRoute: typeof AuthenticatedFusionfitIndexRouteImport
      parentRoute: typeof AuthenticatedFusionfitRoute
    }
    '/_authenticated/fusionfit/abonnement': {
      id: '/_authenticated/fusionfit/abonnement'
      path: '/abonnement'
      fullPath: '/fusionfit/abonnement'
      preLoaderRoute: typeof AuthenticatedFusionfitAbonnementRouteImport
      parentRoute: typeof AuthenticatedFusionfitRoute
    }
    '/_authenticated/fusionfit/bibliotheque': {
      id: '/_authenticated/fusionfit/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/fusionfit/bibliotheque'
      preLoaderRoute: typeof AuthenticatedFusionfitBibliothequeRouteImport
      parentRoute: typeof AuthenticatedFusionfitRoute
    }
    '/_authenticated/fusionfit/coach': {
      id: '/_authenticated/fusionfit/coach'
      path: '/coach'
      fullPath: '/fusionfit/coach'
      preLoaderRoute: typeof AuthenticatedFusionfitCoachRouteImport
      parentRoute: typeof AuthenticatedFusionfitRoute
    }
    '/_authenticated/fusionfit/creneaux': {
      id: '/_authenticated/fusionfit/creneaux'
      path: '/creneaux'
      fullPath: '/fusionfit/creneaux'
      preLoaderRoute: typeof AuthenticatedFusionfitCreneauxRouteImport
      parentRoute: typeof AuthenticatedFusionfitRoute
    }
    '/_authenticated/fusionfit/escouade': {
      id: '/_authenticated/fusionfit/escouade'
      path: '/escouade'
      fullPath: '/fusionfit/escouade'
      preLoaderRoute: typeof AuthenticatedFusionfitEscouadeRouteImport
      parentRoute: typeof AuthenticatedFusionfitRoute
    }
    '/_authenticated/fusionfit/messagerie': {
      id: '/_authenticated/fusionfit/messagerie'
      path: '/messagerie'
      fullPath: '/fusionfit/messagerie'
      preLoaderRoute: typeof AuthenticatedFusionfitMessagerieRouteImport
      parentRoute: typeof AuthenticatedFusionfitRoute
    }
    '/_authenticated/fusionfit/onboarding': {
      id: '/_authenticated/fusionfit/onboarding'
      path: '/onboarding'
      fullPath: '/fusionfit/onboarding'
      preLoaderRoute: typeof AuthenticatedFusionfitOnboardingRouteImport
      parentRoute: typeof AuthenticatedFusionfitRoute
    }
    '/_authenticated/fusionfit/profil': {
      id: '/_authenticated/fusionfit/profil'
      path: '/profil'
      fullPath: '/fusionfit/profil'
      preLoaderRoute: typeof AuthenticatedFusionfitProfilRouteImport
      parentRoute: typeof AuthenticatedFusionfitRoute
    }
    '/_authenticated/fusionfit/routine': {
      id: '/_authenticated/fusionfit/routine'
      path: '/routine'
      fullPath: '/fusionfit/routine'
      preLoaderRoute: typeof AuthenticatedFusionfitRoutineRouteImport
      parentRoute: typeof AuthenticatedFusionfitRoute
    }
    '/_authenticated/fusionfit/stats': {
      id: '/_authenticated/fusionfit/stats'
      path: '/stats'
      fullPath: '/fusionfit/stats'
      preLoaderRoute: typeof AuthenticatedFusionfitStatsRouteImport
      parentRoute: typeof AuthenticatedFusionfitRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fusionfit/escouade/$abonneId': {
      id: '/_authenticated/fusionfit/escouade/$abonneId'
      path: '/$abonneId'
      fullPath: '/fusionfit/escouade/$abonneId'
      preLoaderRoute: typeof AuthenticatedFusionfitEscouadeAbonneIdRouteImport
      parentRoute: typeof AuthenticatedFusionfitEscouadeRoute
    }
  }
}

interface AuthenticatedFusionfitEscouadeRouteChildren {
  AuthenticatedFusionfitEscouadeAbonneIdRoute: typeof AuthenticatedFusionfitEscouadeAbonneIdRoute
}

const AuthenticatedFusionfitEscouadeRouteChildren: AuthenticatedFusionfitEscouadeRouteChildren =
  {
    AuthenticatedFusionfitEscouadeAbonneIdRoute:
      AuthenticatedFusionfitEscouadeAbonneIdRoute,
  }

const AuthenticatedFusionfitEscouadeRouteWithChildren =
  AuthenticatedFusionfitEscouadeRoute._addFileChildren(
    AuthenticatedFusionfitEscouadeRouteChildren,
  )

interface AuthenticatedFusionfitRouteChildren {
  AuthenticatedFusionfitAbonnementRoute: typeof AuthenticatedFusionfitAbonnementRoute
  AuthenticatedFusionfitBibliothequeRoute: typeof AuthenticatedFusionfitBibliothequeRoute
  AuthenticatedFusionfitCoachRoute: typeof AuthenticatedFusionfitCoachRoute
  AuthenticatedFusionfitCreneauxRoute: typeof AuthenticatedFusionfitCreneauxRoute
  AuthenticatedFusionfitEscouadeRoute: typeof AuthenticatedFusionfitEscouadeRouteWithChildren
  AuthenticatedFusionfitMessagerieRoute: typeof AuthenticatedFusionfitMessagerieRoute
  AuthenticatedFusionfitOnboardingRoute: typeof AuthenticatedFusionfitOnboardingRoute
  AuthenticatedFusionfitProfilRoute: typeof AuthenticatedFusionfitProfilRoute
  AuthenticatedFusionfitRoutineRoute: typeof AuthenticatedFusionfitRoutineRoute
  AuthenticatedFusionfitStatsRoute: typeof AuthenticatedFusionfitStatsRoute
  AuthenticatedFusionfitIndexRoute: typeof AuthenticatedFusionfitIndexRoute
}

const AuthenticatedFusionfitRouteChildren: AuthenticatedFusionfitRouteChildren =
  {
    AuthenticatedFusionfitAbonnementRoute:
      AuthenticatedFusionfitAbonnementRoute,
    AuthenticatedFusionfitBibliothequeRoute:
      AuthenticatedFusionfitBibliothequeRoute,
    AuthenticatedFusionfitCoachRoute: AuthenticatedFusionfitCoachRoute,
    AuthenticatedFusionfitCreneauxRoute: AuthenticatedFusionfitCreneauxRoute,
    AuthenticatedFusionfitEscouadeRoute:
      AuthenticatedFusionfitEscouadeRouteWithChildren,
    AuthenticatedFusionfitMessagerieRoute:
      AuthenticatedFusionfitMessagerieRoute,
    AuthenticatedFusionfitOnboardingRoute:
      AuthenticatedFusionfitOnboardingRoute,
    AuthenticatedFusionfitProfilRoute: AuthenticatedFusionfitProfilRoute,
    AuthenticatedFusionfitRoutineRoute: AuthenticatedFusionfitRoutineRoute,
    AuthenticatedFusionfitStatsRoute: AuthenticatedFusionfitStatsRoute,
    AuthenticatedFusionfitIndexRoute: AuthenticatedFusionfitIndexRoute,
  }

const AuthenticatedFusionfitRouteWithChildren =
  AuthenticatedFusionfitRoute._addFileChildren(
    AuthenticatedFusionfitRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedFusionfitRoute: typeof AuthenticatedFusionfitRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFusionfitRoute: AuthenticatedFusionfitRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
