/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentionsRouteImport } from './routes/mentions'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRelancesRouteImport } from './routes/app.relances'
import { Route as AppParametresRouteImport } from './routes/app.parametres'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppDevisIndexRouteImport } from './routes/app.devis.index'
import { Route as AppDevisNouveauRouteImport } from './routes/app.devis.nouveau'
import { Route as AppDevisIdRouteImport } from './routes/app.devis.$id'

const MentionsRoute = MentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelancesRoute = AppRelancesRouteImport.update({
  id: '/relances',
  path: '/relances',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppDevisIndexRoute = AppDevisIndexRouteImport.update({
  id: '/devis/',
  path: '/devis/',
  getParentRoute: () => AppRoute,
} as any)
const AppDevisNouveauRoute = AppDevisNouveauRouteImport.update({
  id: '/devis/nouveau',
  path: '/devis/nouveau',
  getParentRoute: () => AppRoute,
} as any)
const AppDevisIdRoute = AppDevisIdRouteImport.update({
  id: '/devis/$id',
  path: '/devis/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/mentions': typeof MentionsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/relances': typeof AppRelancesRoute
  '/app/': typeof AppIndexRoute
  '/app/devis/$id': typeof AppDevisIdRoute
  '/app/devis/nouveau': typeof AppDevisNouveauRoute
  '/app/devis/': typeof AppDevisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mentions': typeof MentionsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/relances': typeof AppRelancesRoute
  '/app': typeof AppIndexRoute
  '/app/devis/$id': typeof AppDevisIdRoute
  '/app/devis/nouveau': typeof AppDevisNouveauRoute
  '/app/devis': typeof AppDevisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/mentions': typeof MentionsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/relances': typeof AppRelancesRoute
  '/app/': typeof AppIndexRoute
  '/app/devis/$id': typeof AppDevisIdRoute
  '/app/devis/nouveau': typeof AppDevisNouveauRoute
  '/app/devis/': typeof AppDevisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/mentions'
    | '/app/leads'
    | '/app/parametres'
    | '/app/relances'
    | '/app/'
    | '/app/devis/$id'
    | '/app/devis/nouveau'
    | '/app/devis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mentions'
    | '/app/leads'
    | '/app/parametres'
    | '/app/relances'
    | '/app'
    | '/app/devis/$id'
    | '/app/devis/nouveau'
    | '/app/devis'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/mentions'
    | '/app/leads'
    | '/app/parametres'
    | '/app/relances'
    | '/app/'
    | '/app/devis/$id'
    | '/app/devis/nouveau'
    | '/app/devis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  MentionsRoute: typeof MentionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentions': {
      id: '/mentions'
      path: '/mentions'
      fullPath: '/mentions'
      preLoaderRoute: typeof MentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relances': {
      id: '/app/relances'
      path: '/relances'
      fullPath: '/app/relances'
      preLoaderRoute: typeof AppRelancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parametres': {
      id: '/app/parametres'
      path: '/parametres'
      fullPath: '/app/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devis/': {
      id: '/app/devis/'
      path: '/devis'
      fullPath: '/app/devis/'
      preLoaderRoute: typeof AppDevisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devis/nouveau': {
      id: '/app/devis/nouveau'
      path: '/devis/nouveau'
      fullPath: '/app/devis/nouveau'
      preLoaderRoute: typeof AppDevisNouveauRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devis/$id': {
      id: '/app/devis/$id'
      path: '/devis/$id'
      fullPath: '/app/devis/$id'
      preLoaderRoute: typeof AppDevisIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLeadsRoute: typeof AppLeadsRoute
  AppParametresRoute: typeof AppParametresRoute
  AppRelancesRoute: typeof AppRelancesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDevisIdRoute: typeof AppDevisIdRoute
  AppDevisNouveauRoute: typeof AppDevisNouveauRoute
  AppDevisIndexRoute: typeof AppDevisIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLeadsRoute: AppLeadsRoute,
  AppParametresRoute: AppParametresRoute,
  AppRelancesRoute: AppRelancesRoute,
  AppIndexRoute: AppIndexRoute,
  AppDevisIdRoute: AppDevisIdRoute,
  AppDevisNouveauRoute: AppDevisNouveauRoute,
  AppDevisIndexRoute: AppDevisIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  MentionsRoute: MentionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
